add_lunch_combo xenonhd_crespo-user
add_lunch_combo xenonhd_crespo4g-user
add_lunch_combo xenonhd_emulator-eng
add_lunch_combo xenonhd_maguro-user
add_lunch_combo xenonhd_stingray-user
add_lunch_combo xenonhd_toro-user
add_lunch_combo xenonhd_wingray-user

